version: '3'
services:
    counter1:
        build:
            context: services/counter
        ports:
            - "1231:1234"
        expose:
            - "1234"
        environment:
            NAME: "counter1"
            AMQP_URI: "amqp://rabbitmq:5672"
            REDIS_URI: "amqp://redis:6379"
        depends_on:
            - "rabbitmq"
            - "redis"
    counter2:
        build: 
            context: services/counter
        ports:
            - "1232:1234"
        expose:
            - "1234"
        environment:
            NAME: "counter2"
            AMQP_URI: "amqp://rabbitmq:5672"
            REDIS_URI: "amqp://redis:6379"
        depends_on:
            - "rabbitmq"
            - "redis"
    counter3:
        build: 
            context: services/counter
        ports:
            - "1233:1234"
        expose:
            - "1234"
        environment:
            NAME: "counter3"
            AMQP_URI: "amqp://rabbitmq:5672"
            REDIS_URI: "amqp://redis:6379"
        depends_on:
            - "rabbitmq"
            - "redis"
    balancer:
        build:
            context: services/balancer
        ports:
            - "1234:8000"
        depends_on:
            - "counter1"
            - "counter2"
            - "counter3"
    rabbitmq:
        image: "rabbitmq:3.7-management-alpine"
        expose: 
            - "5672"
        ports:
            - "15673:15672"
    redis:
        image: "redis:5.0-alpine"
        expose:
            - "6379"
        ports:
            - "6378:6379"
