version: '3'
services:
    counter1:
        build: .
        ports:
            - "1231:1234"
        expose:
            - "1234"
        environment:
            NAME: "counter1"
            AMQP_URI: "amqp://rabbitmq:5672"
        depends_on:
            - "rabbitmq"
    counter2:
        build: .
        ports:
            - "1232:1234"
        expose:
            - "1234"
        environment:
            NAME: "counter2"
            AMQP_URI: "amqp://rabbitmq:5672"
        depends_on:
            - "rabbitmq"
    counter3:
        build: .
        ports:
            - "1233:1234"
        expose:
            - "1234"
        environment:
            NAME: "counter3"
            AMQP_URI: "amqp://rabbitmq:5672"
        depends_on:
            - "rabbitmq"
    balancer:
        build:
            context: ./balancer
        ports:
            - "1234:8000"
        depends_on:
            - "counter1"
            - "counter2"
            - "counter3"
    rabbitmq:
        image: "rabbitmq:3.7-management-alpine"
        expose: 
            - "5672"
        ports:
            - "15673:15672"
